#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "skripsi" ]; then
  if ! grep -q "^\[skripsi\]" "$1"; then
    msg=$(cat "$1")
    printf "[skripsi] %s" "$msg" > "$1"
  fi
fi
exit 0
